# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c241ae8237f96ae8363ef942c562ad2e47cd9d5053300fed1fb61ef4e3708aab3046c581bcce697c515b830735bf2d3729a30a882a9a1f3b067761b42eb916d5

test:
  secret_key_base: e336bf55bcddcb291011dfeccec22f3f9341d3c4f0f5df7fcb9d0c1c036cac3fa26252efde38dfe54269fcc2ac980b699dc734666d190113af3b6ddf7dcd195e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
